---
title: "Report"
author: "Murray Jones (520487532)"
subtitle: "Title"
date: "University of Sydney | PHYS1902 | Lab Class X"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    self_contained: yes
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<br>

## Abstract:

<br>

# Full Report

## Initial Analysis of Data Source:

```{r}
data = read.csv("allData.csv")

str(data)
```

```{r}
# Account for late starts:

isSameInitConds = function(is, as) {
    
    if (unique(is$Type)[1] == unique(as$Type)[1] &&
        unique(is$InitAngle)[1] == unique(as$InitAngle)[1] &&
        unique(is$AddedMass)[1] == unique(as$AddedMass)[1]) {
        
        return(1) # Same init conds.
    }
    
    return(0) # Not same init conds.
}

# Get an on time run with same initial conditions.
getOnTime = function(rec) {
    badRun = data[data$Recording == rec, ]
    
    for (rec in unique(data$Recording)) {
        
        testRun = data[data$Recording == rec, ]
        
        if(isSameInitConds(testRun, badRun)) {
        
            testLate = unique(testRun$LateStart)[1]
            
        
            if (testLate == 0) {
                return(testRun)
            }
        }
    }
}


shifts = c()

for (rec in unique(data$Recording)) {
    run = data[data$Recording == rec, ]
    
    late = unique(run$LateStart)[1]
    
    timeshift = 0
    
    if (late) {
        refRun = getOnTime(rec)
        
        target = run$GreenAngle[1]
    
        closePoints = refRun[abs(refRun$GreenAngle - target) < 0.4,]
        
        firstPoint = head(closePoints, 1)
    
        timeshift = firstPoint$Time

    }
    
    for (row in 1:nrow(run)) {
        shifts[length(shifts)+1] = timeshift
    }
}

data$Timeshifts = shifts

data$AdjTime = data$Time + data$Timeshifts

str(data)
```

```{r}
unique(data$InitAngle)
```

```{r}
data$GreenPos = data$GreenDist * data$GreenAngle

run = data[data$Recording == "268", ]
run2 = data[data$Recording == "266", ]
run3 = data[data$Recording == "267", ]


plot(run3$AdjTime, run3$GreenPos, cex=0,
     xlab="Time (s)", ylab="Angular displacement (m·°)")

lines(run$AdjTime, run$GreenPos, col="#114411")
lines(run2$AdjTime, run2$GreenPos, col="#11BB11")
lines(run3$AdjTime, run3$GreenPos, col="#110011")
```

```{r}
analysedRuns = c()


getSameCondRuns = function(source) {
    
    runs = c(source)
    
    #print("-------")
    
    for (rec in unique(data$Recording)) {
        
        if (rec == source) {
            next
        }
        
        if (isSameInitConds(data[data$Recording == rec, ],
                            data[data$Recording == source, ])) {
            
            
            runs[length(runs)+1] = rec
        }
    }
    
    return(runs)
}


difSet = c()
angSet = c()


for (rec in unique(data$Recording)) {
    
    if (rec %in% analysedRuns) {
        next
    }
        
    runs = getSameCondRuns(rec)
    
    for (runNum in runs) {
        analysedRuns[length(analysedRuns)+1] = runNum
    }
    
    run1 = data[data$Recording == runs[1], ]
    run2 = data[data$Recording == runs[2], ]
    run3 = data[data$Recording == runs[3], ]
    
    shortest = 120 * 15 #min(nrow(run1), nrow(run2), nrow(run3))
    
    run1 = head(run1, shortest)
    run2 = head(run2, shortest)
    run3 = head(run3, shortest)
    
    run1$setRun = 1
    run2$setRun = 2
    run3$setRun = 3

    run1$posDif = sqrt((run1$GreenX-run2$GreenX)^2 + (run1$GreenY-run2$GreenY)^2)
    run2$posDif = sqrt((run2$GreenX-run3$GreenX)^2 + (run2$GreenY-run3$GreenY)^2)
    run3$posDif = sqrt((run1$GreenX-run3$GreenX)^2 + (run1$GreenY-run3$GreenY)^2)
    
    totalDif = run1$posDif + run2$posDif + run3$posDif
    
    if (unique(run1$Type) != "angle") {
        next
    }
    
    
    difSum = c(0)
    
    for (elem in totalDif) {
        difSum[length(difSum)+1] = difSum[length(difSum)]+elem/360
    }
    
    difSum = head(difSum, length(difSum)-1)
    
    
    plot(run1$Time, difSum, cex=0.1, ylim=c(0, 12.5), type="l",
         ylab="Cumulative Chaos (m²·s)", xlab="Time (s)",
         col=rgb(unique(run1$InitAngle) / 180,
                 0.1,
                 1-unique(run1$InitAngle) / 180))
    
    par(new=T)
    
    difSet[length(difSet)+1] = sum(totalDif)
    angSet[length(angSet)+1] = unique(run1$InitAngle)
}


par(new=F)

energySet = sin(angSet * (3.14159 / 360))

difSet = difSet / 360

#plot(angSet, difSet, xlim=c(0,180), ylim=c(0, 220000), xlab="Angle (°)", ylab="Chaos over 15 secconds (m²·s)")

plot(energySet, difSet, xlim=c(0,1), ylim=c(0, 12.5), cex=0.8,
     xlab="Initial Energy (J/kg/m)", 
     ylab="Chaos over 15 seconds (m²·s)",
     col="dark green")


# Uncertainty in node position:
err = c()

for (i in 1:length(angSet)) {
    if (i < 4) {
        err[i] = sin(angSet[i] * (3.14159 / 90))
    } else {
        err[i] = 0.3
    }
}


segments(energySet, difSet-err, energySet, difSet+err)

epsilon <- 0.006
segments(energySet-epsilon, difSet-err, energySet+epsilon, difSet-err)
segments(energySet-epsilon, difSet+err, energySet+epsilon, difSet+err)



linearModelEnergyDif = lm(formula = difSet ~ 0+energySet)
summary(linearModelEnergyDif)

abline(linearModelEnergyDif, col="blue")

```

```{r}

```

<br>

# References
